addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.13")
addSbtPlugin("ch.epfl.scala"             % "sbt-missinglink"           % "0.3.1")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("com.geirsson"              % "sbt-ci-release"            % "1.5.3")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"              % "0.9.19")
