name: CI
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: CI ${{ matrix.java }} ${{matrix.scalaVersion}} (${{matrix.scalaPlatform}})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # java: [adopt@1.8, adopt@1.11, 17]
        java: [adopt@1.8, adopt@1.11]
        scalaVersion: ["2_12", "2_13", "3_0"]
        scalaPlatform: ["jvm", "js", "native"]
        exclude:
          - scalaVersion: "3_0"
            scalaPlatform: "native"
    runs-on: ${{ matrix.os }}
    env:
      BUILD_KEY: ${{matrix.scalaVersion}}-${{matrix.scalaPlatform}}
    steps:
      - uses: actions/checkout@v1
      - uses: coursier/cache-action@v3      
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.8

      - name: Setup Scala Native environment
        run: |
            sudo apt-get update
            sudo apt install clang
        if: matrix.scalaPlatform == 'native'

      - name: Test
        run: sbt test-$BUILD_KEY codeQuality-$BUILD_KEY

      - name: SBT Plugin test
        run: sbt pluginTests-$BUILD_KEY
        if: matrix.scalaPlatform == 'jvm' && matrix.scalaVersion == '2_12'

      - name: Check site build
        run: sbt buildSite
        if: matrix.scalaPlatform == 'jvm' && matrix.scalaVersion == '2_13'
  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/master')
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3      
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - run: git fetch --unshallow
      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  publish:
    runs-on: ubuntu-latest
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - uses: coursier/cache-action@v3      
      - run: git fetch --unshallow
      - name: Build site
        run: sbt "buildSite --destination $(pwd)/_site"
      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
