name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v10
      - name: Test
        run: sbt ci
      - name: Check site build
        run: sbt docs/run
