name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: coursier/cache-action@v3      
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Setup Scala Native environment
        run: |
            sudo apt-get update
            sudo apt install clang
      - name: Test
        run: sbt ci
        env:
          JAVA_OPTS: "-XX:MaxMetaspaceSize=1g -Xms1g -Xmx4g -Xss2M -XX:+UseG1GC"
          JVM_OPTS: "-XX:MaxMetaspaceSize=1g -Xms1g -Xmx4g -Xss2M -XX:+UseG1GC"
      - name: Native link
        run: sbt nativeLink
      - name: Check site build
        run: sbt buildSite
