name: CI
on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: CI ${{ matrix.java }} (${{matrix.scalaPlatform}})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [8]
        scalaPlatform: ["jvm", "js", "native"]
    runs-on: ${{ matrix.os }}
    env:
      SCALA_PLATFORM: '${{matrix.scalaPlatform}}'
      SBTN: 'sbt --client'
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3      
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '${{ matrix.java }}'

      - name: SBT remote cache
        id: remote-cache
        uses: actions/cache@v3
        with:
          path: ./.remote-cache
          key: ${{ runner.os }}-remote-cache

      - name: Pull cache 
        run: $SBTN pullRemoteCache-$SCALA_PLATFORM || echo 'remote cache not found'

      - name: Test 2.13
        run: $SBTN "test-2_13-$SCALA_PLATFORM;codeQuality-2_13-$SCALA_PLATFORM"

      - name: Test 3
        run: $SBTN "test-3_3-$SCALA_PLATFORM;codeQuality-3_3-$SCALA_PLATFORM"

      - name: SBT Plugin test
        run: $SBTN pluginTests-2_12-jvm
        if: matrix.scalaPlatform == 'jvm'

      - name: Check site build
        run: $SBTN 'buildSite; buildBlog'
        if: matrix.scalaPlatform == 'jvm'

      - name: Push cache 
        run: $SBTN pushRemoteCache-$SCALA_PLATFORM || echo 'Failed to push remote cache'
        if: github.ref == 'refs/heads/master'
        
  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"

  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/master')
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3      
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '8'
      - run: git fetch --unshallow
      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

  publish:
    runs-on: ubuntu-latest
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/master')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' 
          java-version: '8'
      - uses: coursier/cache-action@v3      
      - run: git fetch --unshallow
      - name: Build site
        run: sbt "buildSite --destination $(pwd)/_site; buildBlog --destination $(pwd)/_site/blog"
      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
