name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: coursier/cache-action@v3      
      - uses: olafurpg/setup-scala@v10
      - name: Test
        run: sbt ci
        env:
          JAVA_OPTS: "-Xmx4G"
      - name: Check site build
        run: sbt buildSite
